name = "krakensync"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "one_to_one"
instances = { min = 2, max = 2, default = 2 }
