name = "rust-example-plans"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "quic"
instances = { min = 2, max = 2, default = 2 }

[[testcases]]
name = "tcp"
instances = { min = 2, max = 2, default = 2 }
